###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"test@mail.com",
    "password":"password",
    "name":"Phantom"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"test@mail.com",
    "password":"password",
    "name":"Phantom"
}